# Generated by Django 4.0.4 on 2022-05-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='alumni_no',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
    ]
