# Generated by Django 4.0.4 on 2022-05-31 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alumni_alumni_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='id',
            new_name='alumni_id',
        ),
    ]
