# Generated by Django 4.0.4 on 2022-06-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_id_alumni_alumni_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='alumni_no',
            new_name='application_no',
        ),
        migrations.RenameField(
            model_name='alumni',
            old_name='alumni_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='alumni',
            name='phone',
            field=models.IntegerField(default=1234567890),
            preserve_default=False,
        ),
    ]
