# Generated by Django 4.0.4 on 2022-06-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_alumni_no_alumni_application_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='alumni_no',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumni',
            name='is_paid',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
