# Generated by Django 4.0.4 on 2022-06-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alumni_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='application_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
