# Generated by Django 4.0.4 on 2022-06-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_alumni_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
